name: Continuous Deployment

on:
  push:
    branches:
      - main  # Triggers immediately when code is merged into main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: train and push
        shell: powershell
        run: |
          conda run -n trl python train_and_push.py
