name: Continuous Integration

on:
  push:
    branches:
      - '**'          # Matches every branch name you push
      - '!main'       # Excludes the main branch (so CD handles main instead)

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: train
        shell: powershell
        run: |
          conda run -n trl python train.py
