name: Local Host Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Test Conda
        shell: powershell
        run: |
          git log --graph --oneline
          conda run -n trl python train.py
